name: Mac OS X Build

on:
  push:
    branches-ignore:
      - master
  release:
    types:
      - created

jobs:
  build:
    runs-on: macos-11

    env:
      DEVELOPER_DIR: /Applications/Xcode.app/Contents/Developer

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup dependency cache
        id: cache
        uses: actions/cache@v2
        with:
          path: deps/build
          key: ${{ runner.os }}-deps-${{ hashFiles('deps/**') }}
          restore-keys: |
            ${{ runner.os }}-deps-

      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          mkdir deps/build
          cd deps/build
          cmake ..
          make -j`nproc`

      - name: Build
        run: |
          mkdir build
          cd build
          cmake .. -DCMAKE_OSX_DEPLOYMENT_TARGET="10.13"
          make -j`nproc`
